version: 0.1

environment_variables:
  plaintext:
    S3_BUCKET: "app.supersheets.io"

phases:
  install:
    commands:
      - echo `npm -v`
      - echo NODE_ENV=$NODE_ENV
      - npm install 
      - npm install --only=dev
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Build CODEBUILD_SOURCE_VERSION $CODEBUILD_SOURCE_VERSION
      - echo Build CODEBUILD_SRC_DIR $CODEBUILD_SRC_DIR
      - NODE_ENV=production npm run build
  post_build:
    commands:
      #- aws s3 cp $CODEBUILD_SRC_DIR/dist/static/fonts/ s3://$S3_BUCKET/static/fonts/ --acl public-read --recursive --cache-control 'max-age=31104000'
      - aws s3 cp $CODEBUILD_SRC_DIR/dist/img/ s3://$S3_BUCKET/img/ --acl public-read --recursive --cache-control 'max-age=31104000'
      - aws s3 cp $CODEBUILD_SRC_DIR/dist/css/ s3://$S3_BUCKET/css/ --acl public-read --recursive --cache-control 'max-age=31104000'
      - aws s3 cp $CODEBUILD_SRC_DIR/dist/js/ s3://$S3_BUCKET/js/ --acl public-read --recursive --cache-control 'max-age=31104000'
      #- aws s3 cp $CODEBUILD_SRC_DIR/dist/favicon.ico s3://$S3_BUCKET/favicon.ico --acl public-read --cache-control 'max-age=31104000'
      - aws s3 cp $CODEBUILD_SRC_DIR/dist/index.html s3://$S3_BUCKET/index.html --acl public-read --cache-control 'no-cache'